# got this off google stfu lmao
# anyways, github workflow for Windows, MacOS and Linux.

name: Noteted App Builder

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    pythonVersion: 3.12

jobs:
    build:
        name: Build for ${{ matrix.os_name }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            include:
              - os: ubuntu-latest
                os_name: Linux
              - os: windows-latest
                os_name: Windows
              - os: macos-latest
                os_name: MacOS

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ env.pythonVersion }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ env.pythonVersion }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Install Tkinter (Linux)
              if: matrix.os_name == 'Linux'
              run: sudo apt-get install -y python3-tk

            - name: Compile with PyInstaller
              run: pyinstaller Noteted.spec

            - name: Rename Build (Linux/macOS)
              if: runner.os != 'Windows'
              run: mv dist/Noteted dist/Noteted-${{ matrix.os_name }}

            - name: Rename Build (Windows)
              if: runner.os == 'Windows'
              run: move dist\Noteted dist\Noteted-${{ matrix.os_name }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Noteted-${{ matrix.os_name }}
                path: dist/Noteted-${{ matrix.os_name }}
